# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1f64d74ab612e644d58c2790fc935fcb651c9d08a4c4b8bc7746e499a8ab4d1f02dac32153c16cdea402dd4601ab8bfb5fecc819347ddcf43ef0706abf38880

test:
  secret_key_base: 2b25fa28de4d9e6d22c47e6efca1dfb049d05e0ee22e43fa0f334715d51773fb79579d2c8115c521ad1922c31ebebca6676cf9f73bb4077cff23d363a15a2d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
